export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION'

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILER = 'LOG_IN_FAILER'
export const LOG_OUT = 'LOG_OUT';  

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST'
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS'
export const FORGET_PASSWORD_FAILER = 'FORGET_PASSWORD_FAILER'

export const ADMIN_ACCOUNT_REQUEST = "ADMIN_ACCOUNT_REQUEST"
export const ADMIN_ACCOUNT_SUCCESS = "ADMIN_ACCOUNT_SUCCESS"
export const ADMIN_ACCOUNT_FAILER = "ADMIN_ACCOUNT_FAILER"
export const ADMIN_RESET_ACCOUNT_REQUEST = "ADMIN_RESET_ACCOUNT_REQUEST"
export const ADMIN_RESET_ACCOUNT_SUCCESS = "ADMIN_RESET_ACCOUNT_SUCCESS"
export const ADMIN_RESET_ACCOUNT_FAILER = "ADMIN_RESET_ACCOUNT_FAILER"

export const RATE_REQUEST = 'RATE_REQUEST'
export const RATE_REQUEST_SUCCESS = 'RATE_REQUEST_SUCCESS'
export const FETCH_RATES = 'FETCH_RATES'
export const FETCH_RATE = 'FETCH_RATE'
export const POST_RATES = 'POST_RATES'
export const UPDATE_RATE = 'UPDATE_RATE'
export const RATE_REQUEST_FAILER = 'RATE_REQUEST_FAILER'

export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS'
export const USERS_REQUEST_FAILER = 'USERS_REQUEST_FAILER'
export const FETCH_USERS = 'FETCH_USERS'
export const DELETE_USERS = 'DELETE_USERS'


export const FETCH_CONTACT ='FETCH_CONTACT'
export const CONTACT_REQUEST ='CONTACT_REQUEST'
export const CONTACT_REQUEST_SUCCESS ='CONTACT_REQUEST_SUCCESS'
export const CONTACT_REQUEST_FAILER ='CONTACT_REQUEST_FAILER'
export const DELETE_CONTACT ='DELETE_CONTACT'

export const WALLETS_REQUEST = 'WALLETS_REQUEST'
export const WALLETS_REQUEST_SUCCESS = 'WALLETS_REQUEST_SUCCESS'
export const WALLETS_REQUEST_FAILER = 'WALLETS_REQUEST_FAILER'
export const FETCH_WALLETS = 'FETCH_WALLETS'
export const DELETE_WALLET = 'DELETE_WALLET'

export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST'
export const TRANSACTION_REQUEST_SUCCESS = 'TRANSACTION_REQUEST_SUCCESS'
export const TRANSACTION_REQUEST_FAILER = 'TRANSACTION_REQUEST_FAILER'
export const FETCH_TRANSACTION = 'FETCH_TRANSACTION'